using System.Text.Json.Serialization;

namespace WebApp.Data
{
  /// <summary>
  /// Represents an error response following RFC 7807 Problem Details standard.
  /// This class accommodates all error response formats from the WebAPI.
  /// </summary>
  public class ErrorResponse
  {
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// Examples: "https://tools.ietf.org/html/rfc7807#section-3.1", "https://tools.ietf.org/html/rfc9110#section-15.5.5"
    /// </summary>
    // We already have System.Text.Json configured to use camelCase globally,
    // [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// Example: "One or more validation errors occurred."
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server.
    /// Examples: 400, 404, 409
    /// </summary>
    public int? Status { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// Examples: "/api/shirts/AA11", "/api/shirts/18"
    /// </summary>
    public string? Instance { get; set; }

    /// <summary>
    /// Validation errors grouped by field name.
    /// Key: Field name (e.g., "id", "size", "createShirtDto")
    /// Value: Array of error messages for that field
    /// </summary>
    public Dictionary<string, string[]>? Errors { get; set; }

    /// <summary>
    /// Unique identifier for correlating this error with server logs.
    /// Example: "00-4e9f32dca61d2a34afe2d1799fadf393-7ba2d364d1c86054-00"
    /// </summary>
    public string? TraceId { get; set; }

    /// <summary>
    /// Gets all error messages as a flat list for easy display.
    /// </summary>
    /// <returns>A list of all error messages from all fields</returns>
    public List<string> GetAllErrorMessages()
    {
      if (Errors == null)
        return new List<string>();

      return Errors.Values
          .SelectMany(messages => messages)
          .ToList();
    }

    /// <summary>
    /// Gets error messages for a specific field.
    /// </summary>
    /// <param name="fieldName">The field name to get errors for</param>
    /// <returns>Array of error messages for the field, or empty array if no errors</returns>
    public string[] GetFieldErrors(string fieldName)
    {
      return Errors?.GetValueOrDefault(fieldName, Array.Empty<string>()) ?? Array.Empty<string>();
    }

    /// <summary>
    /// Checks if there are any errors for a specific field.
    /// </summary>
    /// <param name="fieldName">The field name to check</param>
    /// <returns>True if there are errors for the field, false otherwise</returns>
    public bool HasFieldErrors(string fieldName)
    {
      return Errors?.ContainsKey(fieldName) == true && Errors[fieldName].Length > 0;
    }

    /// <summary>
    /// Gets a user-friendly error message combining title and first error.
    /// </summary>
    /// <returns>A user-friendly error message</returns>
    public string GetDisplayMessage()
    {
      if (!string.IsNullOrWhiteSpace(Title))
      {
        var firstError = GetAllErrorMessages().FirstOrDefault();
        return !string.IsNullOrWhiteSpace(firstError) ? $"{Title}: {firstError}" : Title;
      }

      var firstMessage = GetAllErrorMessages().FirstOrDefault();
      return firstMessage ?? "An error occurred.";
    }

    /// <summary>
    /// Determines if this is a validation error (400 Bad Request).
    /// </summary>
    public bool IsValidationError => Status == 400;

    /// <summary>
    /// Determines if this is a not found error (404 Not Found).
    /// </summary>
    public bool IsNotFoundError => Status == 404;

    /// <summary>
    /// Determines if this is a conflict error (409 Conflict).
    /// </summary>
    public bool IsConflictError => Status == 409;
  }
}
