@WebApiDemo_BaseUrl = http://localhost:5250
# @WebApiDemo_BaseUrl = http://localhost:8000

### 1. Get Hello World
GET {{WebApiDemo_BaseUrl}}/
Accept: application/json

### 2. Get Shirts
# @name getShirts
GET {{WebApiDemo_BaseUrl}}/api/shirts
Accept: application/json

### 3. Get Shirt by Id
@firstItemId = {{getShirts.response.body.$.[0].shirtId}}
GET {{WebApiDemo_BaseUrl}}/api/shirts/{{firstItemId}}
Accept: application/json

### 4. Create New Shirt
# @name createShirt
POST {{WebApiDemo_BaseUrl}}/api/shirts
Content-Type: application/json

{
  "brand": "Nike",
  "color": "Yellow",
  "size": 9,
  "gender": "Male",
  "price": 29.99
}

# ### 4.1. Create New Shirt
# # @name createShirtFromForm
# POST {{WebApiDemo_BaseUrl}}/api/shirts
# Content-Type: application/x-www-form-urlencoded

# size=43&color=Blue&price=19.99

### 5. Update Shirt
@newItemId = {{createShirt.response.body.shirtId}}
PUT {{WebApiDemo_BaseUrl}}/api/shirts/{{newItemId}}
Content-Type: application/json

{
  "brand": "Nike",
  "color": "Yellow",
  "size": 8,
  "gender": "Male",
  "price": 29.99
}



### 6. Patch Shirt
PATCH {{WebApiDemo_BaseUrl}}/api/shirts/{{newItemId}}
Content-Type: application/json

{
  "color": "Red",
  "size": 9,
  "price": 99.99
}

### 7. Delete Shirt
DELETE {{WebApiDemo_BaseUrl}}/api/shirts/{{newItemId}}
